"""add user settings fields

Revision ID: 6b5725b6e565
Revises: e8f4a1c2b3d4
Create Date: 2026-04-12 09:07:12.104788

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6b5725b6e565"
down_revision = "e8f4a1c2b3d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "notifications_enabled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "warranty_reminders_enabled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "preferred_currency",
            sa.String(length=255),
            nullable=False,
            server_default=sa.text("'USD'"),
        ),
    )
    op.alter_column("users", "notifications_enabled", server_default=None)
    op.alter_column("users", "warranty_reminders_enabled", server_default=None)
    op.alter_column("users", "preferred_currency", server_default=None)
    op.drop_constraint(op.f("users_email_key"), "users", type_="unique")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_unique_constraint(
        op.f("users_email_key"),
        "users",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("users", "preferred_currency")
    op.drop_column("users", "warranty_reminders_enabled")
    op.drop_column("users", "notifications_enabled")
    # ### end Alembic commands ###
