version: "3.9"

services:
  db:
    image: postgres:16
    container_name: bfs_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bfs
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bfs"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  backend:
    build:
      context: ../../apps/backend
    container_name: bfs_backend
    environment:
      - PYTHONPATH=/app
    depends_on:
      - db
    env_file:
      - ../../.env
    volumes:
      - ../../apps/backend:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "
      until pg_isready -h db -p 5432 -U postgres -d bfs; do
        echo 'Waiting for database...';
        sleep 2;
      done;
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  frontend:
    build:
      context: ../../apps/frontend
    container_name: bfs_frontend
    volumes:
      - ../../apps/frontend:/app
      - /app/node_modules
    ports:
      - "3000:5173"
    command: npm run dev -- --host

volumes:
  db_data: